# Generated by Django 5.2.2 on 2025-06-18 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to='core.board'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='boards', through='core.BoardMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.board'),
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.category'),
        ),
        migrations.AddField(
            model_name='linkitem',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.note'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='core.note'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.note'),
        ),
        migrations.AddField(
            model_name='notetag',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.note'),
        ),
        migrations.AddField(
            model_name='tabledata',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_data', to='core.note'),
        ),
        migrations.AddField(
            model_name='notetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
        migrations.AddField(
            model_name='voicenote',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_note', to='core.note'),
        ),
        migrations.AlterUniqueTogether(
            name='boardmember',
            unique_together={('board', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='notetag',
            unique_together={('note', 'tag')},
        ),
    ]
