# Generated by Django 5.2.2 on 2025-06-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_board_note_board_boardmember_board_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin'), ('owner', 'Owner')], default='viewer', max_length=20),
        ),
    ]
